# Generated by Django 4.2.22 on 2025-06-08 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('frequency', '频率分析'), ('trend', '趋势分析'), ('pattern', '模式分析'), ('prediction', '预测生成'), ('export', '数据导出')], max_length=20, verbose_name='分析类型')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='分析参数')),
                ('result_summary', models.TextField(blank=True, verbose_name='结果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户分析日志',
                'verbose_name_plural': '用户分析日志',
                'db_table': 'user_analysis_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='user_analys_created_a0c6ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.PositiveSmallIntegerField(verbose_name='球号')),
                ('ball_type', models.CharField(choices=[('red', '红球'), ('blue', '蓝球')], max_length=4, verbose_name='球类型')),
                ('appear_count', models.PositiveIntegerField(default=0, verbose_name='出现次数')),
                ('last_appear_issue', models.CharField(blank=True, max_length=20, null=True, verbose_name='最后出现期号')),
                ('max_interval', models.PositiveIntegerField(default=0, verbose_name='最大间隔')),
                ('avg_interval', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='平均间隔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统计分析',
                'verbose_name_plural': '统计分析',
                'db_table': 'statistics',
                'indexes': [models.Index(fields=['ball_type', 'ball_number'], name='statistics_ball_ty_67b4cf_idx'), models.Index(fields=['appear_count'], name='statistics_appear__8b0416_idx')],
                'unique_together': {('ball_number', 'ball_type')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('frequency', '频率统计'), ('trend', '趋势分析'), ('regression', '线性回归'), ('ensemble', '组合算法')], max_length=20, verbose_name='预测算法')),
                ('target_issue', models.CharField(max_length=20, verbose_name='预测期号')),
                ('predicted_red_balls', models.JSONField(verbose_name='预测红球')),
                ('predicted_blue_ball', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='预测蓝球')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='置信度')),
                ('is_accurate', models.BooleanField(blank=True, null=True, verbose_name='是否准确')),
                ('red_match_count', models.PositiveSmallIntegerField(default=0, verbose_name='红球命中数')),
                ('blue_match', models.BooleanField(default=False, verbose_name='蓝球是否命中')),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='准确率得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预测记录',
                'verbose_name_plural': '预测记录',
                'db_table': 'predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['algorithm'], name='predictions_algorit_7b3d89_idx'), models.Index(fields=['created_at'], name='predictions_created_6eba16_idx')],
            },
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=20, unique=True, verbose_name='期号')),
                ('draw_date', models.DateField(verbose_name='开奖日期')),
                ('red_ball_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球1')),
                ('red_ball_2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球2')),
                ('red_ball_3', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球3')),
                ('red_ball_4', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球4')),
                ('red_ball_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球5')),
                ('red_ball_6', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)], verbose_name='红球6')),
                ('blue_ball', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='蓝球')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '开奖记录',
                'verbose_name_plural': '开奖记录',
                'db_table': 'lottery_results',
                'ordering': ['-draw_date', '-issue'],
                'indexes': [models.Index(fields=['draw_date'], name='lottery_res_draw_da_e9495e_idx'), models.Index(fields=['issue'], name='lottery_res_issue_62eb37_idx')],
            },
        ),
    ]
