# Generated by Django 4.2.22 on 2025-06-08 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('normal', '普通用户'), ('admin', '管理员')], default='normal', max_length=10, verbose_name='用户类型')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('total_analysis_count', models.PositiveIntegerField(default=0, verbose_name='分析次数')),
                ('total_prediction_count', models.PositiveIntegerField(default=0, verbose_name='预测次数')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='lotteryresult',
            index=models.Index(fields=['-draw_date', 'issue'], name='lottery_res_draw_da_7887d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lotteryresult',
            index=models.Index(fields=['red_ball_1', 'red_ball_2', 'red_ball_3'], name='lottery_res_red_bal_ad729d_idx'),
        ),
        migrations.AddIndex(
            model_name='lotteryresult',
            index=models.Index(fields=['blue_ball'], name='lottery_res_blue_ba_927f31_idx'),
        ),
        migrations.AddIndex(
            model_name='lotteryresult',
            index=models.Index(fields=['created_at'], name='lottery_res_created_ba28ea_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['target_issue'], name='predictions_target__a18714_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['-appear_count'], name='statistics_appear__b0f887_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['ball_type', '-appear_count'], name='statistics_ball_ty_e1b77e_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['max_interval'], name='statistics_max_int_11a551_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['last_appear_issue'], name='statistics_last_ap_f42374_idx'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=models.Index(fields=['updated_at'], name='statistics_updated_2b8378_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='user_profil_user_ty_fe6856_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='user_profil_created_26443b_idx'),
        ),
    ]
