# Generated by Django 4.2.22 on 2025-06-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_fix_userprofile_user_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_type', models.CharField(choices=[('lottery_result', '开奖结果'), ('prediction', '预测记录'), ('analysis', '分析结果'), ('number_set', '号码组合')], max_length=20, verbose_name='收藏类型')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('content_data', models.JSONField(blank=True, null=True, verbose_name='收藏内容')),
                ('title', models.CharField(max_length=200, verbose_name='收藏标题')),
                ('description', models.TextField(blank=True, verbose_name='收藏描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user_profile', 'favorite_type'], name='user_favori_user_pr_7e4cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['favorite_type'], name='user_favori_favorit_aa8f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['created_at'], name='user_favori_created_9bb5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['is_public'], name='user_favori_is_publ_b56a1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user_profile', 'favorite_type', 'object_id')},
        ),
    ]
