# Generated by Django 4.2.22 on 2025-06-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_add_user_favorite_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysislog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.userprofile', verbose_name='用户'),
        ),
        migrations.RenameField(
            model_name='useranalysislog',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameIndex(
            model_name='userfavorite',
            new_name='user_favori_user_pr_d15524_idx',
            old_name='user_favori_user_pr_7e4cf7_idx',
        ),
        migrations.RenameIndex(
            model_name='userfavorite',
            new_name='user_favori_favorit_c3139a_idx',
            old_name='user_favori_favorit_aa8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='userfavorite',
            new_name='user_favori_created_32beaf_idx',
            old_name='user_favori_created_9bb5b3_idx',
        ),
        migrations.RenameIndex(
            model_name='userfavorite',
            new_name='user_favori_is_publ_412502_idx',
            old_name='user_favori_is_publ_b56a1e_idx',
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite_type',
            field=models.CharField(choices=[('lottery_result', '开奖结果'), ('prediction', '预测记录'), ('number_set', '号码组合')], max_length=20, verbose_name='收藏类型'),
        ),
        migrations.AddIndex(
            model_name='useranalysislog',
            index=models.Index(fields=['user_profile', 'created_at'], name='user_analys_user_id_6a8aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalysislog',
            index=models.Index(fields=['analysis_type'], name='user_analys_analysi_8aa389_idx'),
        ),
    ]
