# Generated by Django 4.2.22 on 2025-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_update_favorite_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite_type',
            field=models.CharField(choices=[('lottery_result', '开奖结果'), ('prediction', '预测记录'), ('analysis', '分析结果'), ('number_set', '号码组合')], max_length=20, verbose_name='收藏类型'),
        ),
    ]
