# Generated by Django 4.2.22 on 2025-06-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0008_alter_userfavorite_favorite_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_type', models.CharField(choices=[('crawler', '爬虫配置'), ('analysis', '分析配置'), ('system', '系统配置'), ('notification', '通知配置')], max_length=20, verbose_name='配置类型')),
                ('value', models.TextField(verbose_name='配置值')),
                ('default_value', models.TextField(blank=True, verbose_name='默认值')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('float', '小数'), ('boolean', '布尔值'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='数据类型')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='验证规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
                'ordering': ['config_type', 'key'],
                'indexes': [models.Index(fields=['key'], name='system_conf_key_4990ef_idx'), models.Index(fields=['config_type'], name='system_conf_config__b00bc2_idx'), models.Index(fields=['is_active'], name='system_conf_is_acti_b5f3d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=10, verbose_name='日志级别')),
                ('log_type', models.CharField(choices=[('system', '系统日志'), ('user', '用户日志'), ('crawler', '爬虫日志'), ('api', 'API日志'), ('security', '安全日志')], max_length=20, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='模块名称')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='函数名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求数据')),
                ('exception_type', models.CharField(blank=True, max_length=200, verbose_name='异常类型')),
                ('exception_message', models.TextField(blank=True, verbose_name='异常消息')),
                ('traceback', models.TextField(blank=True, verbose_name='异常堆栈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='system_logs_level_245244_idx'), models.Index(fields=['log_type'], name='system_logs_log_typ_c8f71a_idx'), models.Index(fields=['created_at'], name='system_logs_created_2e006d_idx'), models.Index(fields=['user'], name='system_logs_user_id_85bc8b_idx'), models.Index(fields=['ip_address'], name='system_logs_ip_addr_0992b7_idx')],
            },
        ),
    ]
